<a href="https://colab.research.google.com/github/CosentinoFacu/Simulacion-Clinico/blob/main/Creando_Nuevo_Dataset_Reconocimiento_de_digitos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [226]:
from sklearn.datasets import load_digits
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

datos = datasets.load_digits()
df=pd.DataFrame(data=datos.data, columns=datos.feature_names)
df["target"]=datos.target

aux = datos.data
rows, columns = aux.shape
newdata = np.ones([rows,16])
#print(aux.shape)

cant,_=aux.shape
#print(cant)

for k in range (cant):
  wa_newdata = np.ones([1,16])
  #print(wa_newdata)
  aux = datos.images[k]
  #print(aux)
  acum=0

  for j in range (8):
    acum=0
    for i in range (8):
      acum=acum+aux[j,i]
    wa_newdata[0,j]=acum

  #print(wa_newdata)

  for j in range (8):
    acum=0
    for i in range (8):
      acum=acum+aux[i,j]
    wa_newdata[0,j+8]=acum
  #print(wa_newdata)
  for i in range (16):
    newdata[k,i]=wa_newdata[0,i]


#print(wa_newdata)
columnas = ['sf1','sf2','sf3','sf4','sf5','sf6','sf7','sf8','sc1','sc2','sc3','sc4','sc5','sc6','sc7','sc8']
print(newdata.shape)

newdf=pd.DataFrame(data=newdata, columns=columnas)
newdf["target"]=datos.target

newdf

(1797, 16)

,sf1,sf2,sf3,sf4,sf5,sf6,sf7,sf8,sc1,sc2,sc3,sc4,sc5,sc6,sc7,sc8,target
0,28.0,58.0,39.0,32.0,30.0,35.0,43.0,29.0,0.0,18.0,84.0,48.0,40.0,68.0,36.0,0.0,0
1,30.0,36.0,40.0,56.0,36.0,39.0,39.0,37.0,0.0,7.0,21.0,113.0,125.0,47.0,0.0,0.0,1
2,31.0,48.0,45.0,33.0,38.0,46.0,64.0,39.0,0.0,13.0,49.0,87.0,100.0,81.0,14.0,0.0,2
3,36.0,46.0,29.0,29.0,26.0,19.0,40.0,42.0,0.0,10.0,38.0,67.0,83.0,51.0,18.0,0.0,3
4,12.0,15.0,24.0,39.0,53.0,65.0,28.0,22.0,0.0,9.0,39.0,67.0,69.0,57.0,17.0,0.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1792,33.0,62.0,49.0,65.0,32.0,20.0,39.0,40.0,0.0,5.0,55.0,71.0,70.0,110.0,29.0,0.0,9
1793,47.0,60.0,45.0,38.0,44.0,58.0,65.0,42.0,0.0,21.0,107.0,77.0,64.0,102.0,28.0,0.0,0
1794,28.0,40.0,62.0,47.0,45.0,61.0,61.0,30.0,0.0,0.0,80.0,112.0,109.0,67.0,6.0,0.0,8
1795,19.0,62.0,53.0,58.0,53.0,18.0,36.0,45.0,0.0,9.0,62.0,76.0,70.0,107.0,20.0,0.0,9
1796,33.0,39.0,53.0,47.0,54.0,52.0,66.0,48.0,0.0,15.0,98.0,102.0,79.0,83.0,15.0,0.0,8

In [241]:
#Guardamos el Nuevo Dataset
from google.colab import files

newdf.to_csv('output.csv', encoding = 'utf-8-sig') 
files.download('output.csv')

In [253]:
#Descargamos y mostramos el Nuevo Dataset
import io
from google.colab import files 
  
  
uploaded = files.upload()
df2 = pd.read_csv(io.BytesIO(uploaded['output.csv']))
nada = df2.pop('Unnamed: 0')
df2

,sf1,sf2,sf3,sf4,sf5,sf6,sf7,sf8,sc1,sc2,sc3,sc4,sc5,sc6,sc7,sc8,target
0,28.0,58.0,39.0,32.0,30.0,35.0,43.0,29.0,0.0,18.0,84.0,48.0,40.0,68.0,36.0,0.0,0
1,30.0,36.0,40.0,56.0,36.0,39.0,39.0,37.0,0.0,7.0,21.0,113.0,125.0,47.0,0.0,0.0,1
2,31.0,48.0,45.0,33.0,38.0,46.0,64.0,39.0,0.0,13.0,49.0,87.0,100.0,81.0,14.0,0.0,2
3,36.0,46.0,29.0,29.0,26.0,19.0,40.0,42.0,0.0,10.0,38.0,67.0,83.0,51.0,18.0,0.0,3
4,12.0,15.0,24.0,39.0,53.0,65.0,28.0,22.0,0.0,9.0,39.0,67.0,69.0,57.0,17.0,0.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1792,33.0,62.0,49.0,65.0,32.0,20.0,39.0,40.0,0.0,5.0,55.0,71.0,70.0,110.0,29.0,0.0,9
1793,47.0,60.0,45.0,38.0,44.0,58.0,65.0,42.0,0.0,21.0,107.0,77.0,64.0,102.0,28.0,0.0,0
1794,28.0,40.0,62.0,47.0,45.0,61.0,61.0,30.0,0.0,0.0,80.0,112.0,109.0,67.0,6.0,0.0,8
1795,19.0,62.0,53.0,58.0,53.0,18.0,36.0,45.0,0.0,9.0,62.0,76.0,70.0,107.0,20.0,0.0,9
1796,33.0,39.0,53.0,47.0,54.0,52.0,66.0,48.0,0.0,15.0,98.0,102.0,79.0,83.0,15.0,0.0,8